### ISSUE TITLE
Cannot POST /MMM-HomeAutomationNotifications

### ISSUE THREAD

**Issue by sglock** [john3300/MMM-HomeAutomationNotifications#1]
Hi,
found your module and think it is something many will be interested in. Since I am new to HTTP requests and don't fully understand how it works maybe someone can help figuring out what I am doing wrong. 
I am running an Openhab server on a seperate Raspberry on the same network.

`var config = {
	address: "0.0.0.0",
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.2.1/120", "192.168.2.1/24"]`

I can ping and connect thru ssh from the Openhab server to MagicMirror.

I tried to post messages through openhab HTTP Actions to MagicMirror. Since I dind't get that to work I tried to send the POST request via curl from the Openhab server (192.168.2.214)  to MagicMirror (192.168.2.213). 

When executing:

`curl -X POST http://192.168.2.213:8080/MMM-HomeAutomationNotifications?type=WARNING&message=Test` 

I always get the answer:

> html lang="en"
head
meta charset="utf-8"
title Error /title
/head
body
pre Cannot POST /MMM-HomeAutomationNotifications /pre
/body
/html

I have no idea what to look for. Maybe someone can point me in the right direction.
Thanks for any suggestions.

**Comment by john3300** [comment]
Did you enable the module in your config file as well?

It can also be helpful to add the -v flag to your curl call to get more
details like the HTTP status code.

**Comment by sglock** [comment]
Enable? You mean git pull and config file? Yes module is enabled:
`{
			module: "MMM-HomeAutomationNotfications",
        position: "bottom_right",	// This can be any of the regions.
        config: {
            // The config property is optional.
            // See 'Configuration options' for more information.
        	}
		},`
Here are the results of
`curl -v -X POST http://192.168.2.213:8080/MMM-HomeAutomationNotifications?type=WARNING&message=Test`

Trying 192.168.2.213...
TCP_NODELAY set
Expire in 200 ms for 4 (transfer 0xd02880)
Connected to 192.168.2.213 (192.168.2.213) port 8080 (#0)
POST /MMM-HomeAutomationNotifications?type=WARNING HTTP/1.1
Host: 192.168.2.213:8080
User-Agent: curl/7.64.0
Accept: */*

HTTP/1.1 404 Not Found
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Security-Policy: default-src 'none'
Content-Type: text/html; charset=utf-8
Content-Length: 171
Date: Sun, 23 Aug 2020 16:15:38 GMT
Connection: keep-alive

Since I am new to this I can't make much sense of the information. Can you tell me what that means?

**Comment by john3300** [comment]
So this line is the important one:
  HTTP/1.1 404 Not Found

Basically that means that it can't find the address you tried to connect to.

If you just go to 192.168.2.213:8080 with a web browser do you see
anything?  That should show you what your mirror is displaying.

**Comment by sglock** [comment]
> If you just go to 192.168.2.213:8080 with a web browser do you see
anything?  That should show you what your mirror is displaying.

Yes, just checked ... opened address in the browser and I can see the mirror content, all modules are visible. Seems to me that I can't find **/MMM-HomeAutomationNotifications**.

**Comment by john3300** [comment]
So that means your ipAddress, port, ipWhiteList part of your config is definitely working.  So now the question is if the module is loading properly.  I think the easiest way to test that is to add a header to the module config and make sure that shows up on the mirror:

{
    module: "MMM-HomeAutomationNotifications",
    position: "bottom_bar",
    header: "Test header"
}

Save the file and then restart the mirror so it picks up the change.

**Comment by sglock** [comment]
OK, now we are getting somewhere. The module shows with Test header if I put it in the position "bottom_bar" and I, as I use the "MMM-pages" module, I put it in the fixed section of the config.
After I try teh curl command again this is the aswer:

`curl -v -X POST http://192.168.2.213:8080/MMM-HomeAutomationNotifications?type=WARNING&message=Test`

type=WARNING&message=Front%20door%unlocked

   Trying 192.168.2.213...
 TCP_NODELAY set
 Expire in 200 ms for 4 (transfer 0x384880)
 Connected to 192.168.2.213 (192.168.2.213) port 8080 (#0)
 POST /MMM-HomeAutomationNotifications?type=WARNING HTTP/1.1
 Host: 192.168.2.213:8080
 User-Agent: curl/7.64.0
 Accept: /

 HTTP/1.1 400 Bad Request
 X-DNS-Prefetch-Control: off
 X-Frame-Options: SAMEORIGIN
 Strict-Transport-Security: max-age=15552000; includeSubDomains
 X-Download-Options: noopen
 X-Content-Type-Options: nosniff
 X-XSS-Protection: 1; mode=block
 Content-Type: text/html; charset=utf-8
 Content-Length: 36
 ETag: W/"24-mhAU2KpEuvW7EhlU8DJtWEPFXGs"
 Date: Mon, 24 Aug 2020 16:37:43 GMT
 Connection: keep-alive

 Connection #0 to host 192.168.2.213 left intact
Query parameter message is required!
[1]+  Fertig                  curl -v -X POST http://192.168.2.213:8080/MMM-HomeAutomationNotifications?type=WARNING

**Comment by john3300** [comment]
Yes, this is better.  The `HTTP/1.1 400 Bad Request` means that the request was made successfully, but there was a problem with it and it was rejected.

The very end of the output shows `Query parameter message is required!` which is an error message from the module stating that the message query parameter was missing.  Which if you look at the curl command shown in the very last line looks to be true.

**Comment by sglock** [comment]
Ok got it to work with the curl command .... kind of:

`curl -v -X POST "http://192.168.2.213:8080/MMM-HomeAutomationNotifications?type=WARNING&message=Front%20door%unlocked"`

notice the quotation marks in the command. Only point now ist that teh message is shown without the spaces but like this:
>Front%20door%unlocked

Will try to get it to work with openhab now.

**Comment by john3300** [comment]
Your second `%` needs to be `%20`.

**Comment by sglock** [comment]
Yep that was ist ... now the message is shown correctly! Thx for your help and keep up the good work!

PS: Works like a charm with openhab!!!
