### ISSUE TITLE
Module does not show up | no helper found for MMM-HomeAutomationNotifications

### ISSUE THREAD

**Issue by ghost** [john3300/MMM-HomeAutomationNotifications#2]
Hello

I've just installed this module, config sounds ok but the module does not show up in the interface. curl post says cannot post. Sounds like the helper module is not registered.

Magicmirror log just says : no helper found for MMM-HomeAutomationNotifications
My config for the module is the one in your README. 

Any idea ?

**Comment by john3300** [comment]
If the POST is failing then I would start by looking at how you installed the module files. All the files in this repo should be at MagicMirror/modules/MMM-HomeAutomationNotifications.

Since there is nothing displayed by default, it can also be helpful to set a header value to see if the module is being loaded at all.

**Comment by ghost** [comment]
Hello @john3300 , module is well located in modules as any other modules I have already installed.
I am running the latest version of MM. I've also set a header and it is not appearing on the page.

My concern here is why MM says : no helper found for MMM-HomeAutomationNotifications during the start.
Could you check your logs to see if you get the same behavior ?

**Comment by john3300** [comment]
Nope, my log shows the module IS loaded:
```
[2020-10-02 09:19:30.515] [LOG]    Initializing new module helper ...
[2020-10-02 09:19:30.517] [LOG]    Module helper loaded: MMM-HomeAutomationNotifications
```

**Comment by ghost** [comment]
I don't understand, I used to use MM and add module.
I've just clone your github into modules, copy paste the config section.. and it says no helper found for MMM-HomeAutomationNotifications.

Are you using the latest version of MM ?

**Comment by john3300** [comment]
Yes, I'm on the very latest version.  Sorry man, I don't know what else to
tell you.  But if you debug it further and figure something out do let me
know if there's any improvements that could be made to the code.

**Comment by HA-TB303** [comment]
I'm having a similar issue:

POST http://192.168.207.180:8080/MMM-HomeAutomationNotifications?type=WARNING&message=Front%20door%20unlocked

![image](https://user-images.githubusercontent.com/9609805/146007222-5a1c507d-0b9f-4af4-8066-dd975bfe4783.png)
